name: Terraform Apply (staging)

on:
  push:
    branches:
      - staging

jobs:
  terraform-apply-stg:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/stg
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
