name: Terraform Apply (staging)

on:
  push:
    branches:
      - staging

jobs:
  terraform-apply-stg:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/stg
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init
        run: terraform init \
          -backend-config="bucket=petcamera-terraform-state" \
          -backend-config="key=stg/terraform.tfstate" \
          -backend-config="region=ap-northeast-1"

      - name: Terraform Plan
        run: terraform plan -var-file=environment.tfvars -out=tfplan.binary

      - name: Terraform Apply
        run: terraform apply -var-file=environment.tfvars -auto-approve tfplan.binary
